fix: date validation on student form, instructor duplicate fix on student grp, instructor with same employee id fix (#20072)
* fix: date validation on inpatient record, else condition removing on clinical prcd templ which is not req

* fix:Pricing Rule error AttributeError: 'str' object has no attribute 'get' #19770

* fix:Pricing Rule error AttributeError: 'str' object has no attribute 'get' #19770

* fix: joining and relieving Date can be on same date as valid use case

* fix-education: date of birth validation

* fix:Sibling child table filtering for duplacacy on student form

* fix:Sibling child table filtering for duplacacy on student form

* fix:Sibling child table filtering for duplacacy on student form

* fix: date validation on student form, instructor duplicacy fix on student grp, instructor with same employee id fix

* fix: date validation on student form, instructor duplicacy fix on student grp, instructor with same employee id fix

* fix: Exclude current record while validating duplicate employee

Co-authored-by: Nabin Hait <nabinhait@gmail.com>